### ISSUE TITLE
Typo in arriving/welcome.rst

### ISSUE THREAD

**Issue by NotaCS** [scilus/scil-documentation#35]
Hi,
Just to signal that there is a typo in a command line in the doc for "Onboarding new students":
The command line to mount braindata lack a colon after "usherbrooke.ca"
It's written `sshfs USER@braindata.scil.usherbrooke.ca/braindata braindata`
but should be `sshfs USER@braindata.scil.usherbrooke.ca:/braindata braindata`

Also, the instructions don't exactly match those in heavy/storage.rst:
There, it's indicated that we should add the directory to the root, while in the onboarding page, it's written to create the dir in our home.

Bests,
Victor

**Comment by EmmaRenauld** [comment]
Thanks! I'll check that!
