### ISSUE TITLE
Broken link to the TractoFlow doc

### ISSUE THREAD

**Issue by NotaCS** [scilus/scil-documentation#36]
Hi, me again,

The link to how to install TractoFlow on our_tools/tractoflow.rst is broken.
Right now, it's 
[https://tractoflow-documentation.readthedocs.io/en/latest/installation/before_install.html](https://tractoflow-documentation.readthedocs.io/en/latest/installation/before_install.html)
and should be 
[https://tractoflow-documentation.readthedocs.io/en/latest/installation/install.html](https://tractoflow-documentation.readthedocs.io/en/latest/installation/install.html)

Cheers,
Victor

**Comment by NotaCS** [comment]
Could also be [https://tractoflow-documentation.readthedocs.io/en/latest/installation/requirements.html](https://tractoflow-documentation.readthedocs.io/en/latest/installation/requirements.html) I guess.

**Comment by EmmaRenauld** [comment]
Thanks! I actually spotted that one a long time ago put my pull requests haven't been accepted in ages. I'll try to remind people.
