### ISSUE TITLE
Scholarships tab redirects to outdated websites

### ISSUE THREAD

**Issue by CHrlS98** [scilus/scil-documentation#52]
Outdated or non-existing pages:
* The links for FRQ and QBIN redirect to unexisting pages.
* CONP redirects to 2020 competition.

I may have missed others. It would be worth updating.

Let me know if you need help, I have my hands in scholarship applications these days anyway.

**Comment by EmmaRenauld** [comment]
Fixed in PR #53 ; if you want to review!
